### ISSUE TITLE
Potential problem with private chats?

### ISSUE THREAD

**Issue by dguido** [llimllib/slask#17]
I haven't fully investigated this bug yet, but I think this happens when I invite the bot to a private channel and try interacting with it.
```
2015-01-26T23:05:19.055547+00:00 app[worker.1]: Traceback (most recent call last):
2015-01-26T23:05:19.055569+00:00 app[worker.1]:   File "slask.py", line 117, in <module>
2015-01-26T23:05:19.055590+00:00 app[worker.1]:     main(config)
2015-01-26T23:05:19.055626+00:00 app[worker.1]:   File "slask.py", line 108, in main
2015-01-26T23:05:19.055665+00:00 app[worker.1]:     client.rtm_send_message(event["channel"], response)
2015-01-26T23:05:19.055721+00:00 app[worker.1]:     return self.server.channels.find(channel).send_message(message)
2015-01-26T23:05:19.055696+00:00 app[worker.1]:   File "/app/slackclient/_client.py", line 36, in rtm_send_message
2015-01-26T23:05:19.055825+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'send_message'
```

**Comment by llimllib** [comment]
Reproduced!

1. Create a "private group"
2. invite slask
3. send slask a message that it tries to handle
4. watch slask crash and burn

**Comment by llimllib** [comment]
It appears to be a bug in slackclient (which code is provided by @slackhq):

```$ python slask.py
> /Users/llimllib/code/slask/slask.py(110)main()
    109                         import ipdb; ipdb.set_trace()
--> 110                         client.rtm_send_message(event["channel"], response)
    111             time.sleep(1)

ipdb> p response
u'http://31.media.tumblr.com/a5e39d12cb16e7237836dc0552aca4bf/tumblr_mi32nihmX31r4y42jo1_500.gif'
ipdb> p event["channel"]
u'G03FF7Q3C'
ipdb> s
--Call--
> /Users/llimllib/code/slask/slackclient/_client.py(35)rtm_send_message()
     34
---> 35     def rtm_send_message(self, channel, message):
     36         return self.server.channels.find(channel).send_message(message)

ipdb> self.server.channels
[id : C02L9JD16
name : general
members : [u'U02L9JD0Y', u'U035JM635']
server : username : slask
domain : llimllib
webso
, id : C02L9JD18
name : random
members : [u'U02L9JD0Y', u'U035JM635']
server : username : slask
domain : llimllib
webso
, id : D035JM639
name : D035JM639
members : []
server : username : slask
domain : llimllib
webso
, id : D035JM63B
name : D035JM63B
members : []
server : username : slask
domain : llimllib
webso
]```

slack sends a response to a private channel, slackclient doesn't find it in `self.server.channels`, and so it bugs out.

**Comment by dguido** [comment]
Coooooool. Looks like you understand this bug a bit more than I do. File away!
https://github.com/slackhq/python-slackclient/issues

**Comment by llimllib** [comment]
Nah, they don't fix issues in there quick enough for me. Fix incoming :bowtie:

**Comment by llimllib** [comment]
No fair me making fun of them! They fixed it in https://github.com/slackhq/python-slackclient/commit/2fd66f6b9d5b62bf9d91c05f63112fecbe614529 and I didn't update.
